### ISSUE TITLE
Have a flag to ignore unsupported OpenAPI keys instead of blowing up

### ISSUE THREAD

**Issue by YannickMeeus** [smartlyio/oats#54]
Yo! So we're trying to be sneaky and actually use some of the more advanced features of the OpenAPI spec, such as 'security'.

Now, you have been sneaky by asserting that such a thing is not there, and if it is, you break all the things.

Would it make sense to either configure oats so that you can explicitly allow and/or ignore unsupported keys, or even default to this behaviour?

**Comment by sakari** [comment]
@YannickMeeus, sure. I would prefer a way to do this so that you would opt in to to it though so as not to silently change behaviour from the expected.

**Comment by YannickMeeus** [comment]
That makes sense to me. Is it alright if I have a stab at doing this in the near™ future?

**Comment by sakari** [comment]
sure. as you may have noticed I do not have notifications on github 😬

**Comment by YannickMeeus** [comment]
@sakari I guessed as much 😀
