### ISSUE TITLE
Support for anyOf keyword

### ISSUE THREAD

**Issue by heikkilavanti** [smartlyio/oats#68]
This is at the same time an enhancement request and bug report :)

Noticed that oats does not support the keyword `anyOf` but does support `oneOf`, which results in a union type. According to OpenAPI spec:
```
oneOf – validates the value against exactly one of the subschemas
allOf – validates the value against all the subschemas
anyOf – validates the value against any (one or more) of the subschemas
```
This coupled with the fact that TypeScript does not "natively" support exclusive union types - see [this](https://github.com/Microsoft/TypeScript/issues/14094) - makes me believe that actually oats should support `anyOf` instead of `oneOf`.

For `oneOf`, I can come up with two options:
1. use TS union types and live with the fact that these are not correct in the strictest sense, or
2. create a mutually exclusive Generic that works for n types.

**Comment by heikkilavanti** [comment]
Got an explanation as how this is implemented at the moment => misunderstanding on my part :)
Closing....

**Comment by goalaleo** [comment]
> Got an explanation as how this is implemented at the moment => misunderstanding on my part :)
Closing....
 
@sakari any idea what this explanation was? We'd still like to have support for `anyOf` in pena
